In [1]:
import numpy as np

Array Operations

##### Arithmatic operations ######

In [4]:
a1=np.arange(1,6)
a2=np.arange(6,11)
a1,a2

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [5]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [6]:
a1-a2

array([-5, -5, -5, -5, -5])

In [7]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [8]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [9]:
a1//a2

array([0, 0, 0, 0, 0])

#### Broadcasting ####

In [10]:
l=[10,20,30,40,50]
arr=np.array(l)
arr

array([10, 20, 30, 40, 50])

In [11]:
arr+10

array([20, 30, 40, 50, 60])

In [12]:
arr*10

array([100, 200, 300, 400, 500])

#### Deep and Shallow Copy ####

In [13]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [14]:
slice=a[:5]
slice

array([1, 2, 3, 4, 5])

In [15]:
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [16]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
b=a
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
b[0]=99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

#### Matrix Operations ####

In [21]:
A=np.arange(1,5).reshape(2,2)
A

array([[1, 2],
       [3, 4]])

In [23]:
B=np.arange(5,9).reshape(2,2)
B

array([[5, 6],
       [7, 8]])

In [24]:
mul=A@B
mul

array([[19, 22],
       [43, 50]])

In [25]:
transpose=A.T
transpose

array([[1, 3],
       [2, 4]])

#### Advanced Array Manipulations ####

In [26]:
a=np.arange(1,6)
b=np.arange(6,11)
a,b

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

STACKING

In [28]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [29]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

SPLITTING

In [32]:
c=np.arange(1,17).reshape(4,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [33]:
np.hsplit(c,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [34]:
np.vsplit(c,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]