Numpy indexing and slicing of vectors

In [1]:
import numpy as np

In [3]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [7]:
arr[1:6:3]

array([2, 5])

In [8]:
arr[:5]

array([1, 2, 3, 4, 5])

In [9]:
arr[1::]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

Numpy Indexing and slicing of a Matrix

In [10]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr[0]

array([1, 2, 3, 4, 5])

In [12]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [13]:
arr[0,0]

np.int64(1)

In [14]:
arr[5,2]

np.int64(28)

In [17]:
arr[2:4,1:3]

array([[12, 13],
       [17, 18]])

In [19]:
arr[4:,3:]

array([[24, 25],
       [29, 30]])

In [22]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

Boolean Indexing

In [24]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [28]:
arr=arr[bool_index]
arr

array([ 2,  4,  6,  8, 10])