In [3]:
import numpy as np

Basic Array Creation

In [4]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
a=[1,2,3.5,"hello"]
a

[1, 2, 3.5, 'hello']

In [8]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(l)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation function

In [11]:
arr1=np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr2=np.zeros(5)
arr2

array([0., 0., 0., 0., 0.])

In [14]:
arr2=np.zeros((2,6))
arr2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
arr3=np.ones((4,3))
arr3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
arr4=np.linspace(1,10,5)
arr4

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

Random Generating Functions

In [17]:
np.random.rand(5)

array([0.8868552 , 0.00705376, 0.27430203, 0.23093254, 0.70789901])

In [18]:
np.random.randn(6)

array([-0.08564204,  0.39139075, -0.2866923 ,  0.17891622,  1.00814323,
       -0.33018291])

In [19]:
np.random.randint(1,10,5)

array([3, 4, 3, 4, 1], dtype=int32)

Array Attribute

In [25]:
arr=np.array([[1,2,3,4,5],[2,4,3,2,5],[1,2,3,2,1]])
arr

array([[1, 2, 3, 4, 5],
       [2, 4, 3, 2, 5],
       [1, 2, 3, 2, 1]])

In [26]:
arr.shape

(3, 5)

In [27]:
arr.size

15

In [28]:
arr.dtype

dtype('int64')

Array Methods

In [31]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr.min()

np.int64(1)

In [34]:
arr.max()


np.int64(6)

In [35]:
arr.sum()

np.int64(21)

In [36]:
np.sum(arr,axis=0)

array([5, 7, 9])

In [37]:
np.sum(arr,axis=1)

array([ 6, 15])

In [38]:
arr.mean()

np.float64(3.5)

In [39]:
arr.std()

np.float64(1.707825127659933)

In [40]:
arr.argmin()

np.int64(0)

In [41]:
arr.argmax()

np.int64(5)

Reshape And Resize

In [43]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [46]:
arr.reshape(6,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])