In [1]:
import numpy as np

#### Valid Sudoko ####

In [3]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])


sum of each row should be 45 
sum of each column should be 45 
sum of each 3x3 should be 45


In [5]:
b=np.sum(s,axis=1)
for i in b:
    if (i==45):
        print("sudoko valid for row")

sudoko valid for row
sudoko valid for row
sudoko valid for row
sudoko valid for row
sudoko valid for row
sudoko valid for row
sudoko valid for row
sudoko valid for row
sudoko valid for row


In [6]:
b=np.sum(s,axis=0)
for i in b:
    if (i==45):
        print("sudoko valid for column")

sudoko valid for column
sudoko valid for column
sudoko valid for column
sudoko valid for column
sudoko valid for column
sudoko valid for column
sudoko valid for column
sudoko valid for column
sudoko valid for column


In [8]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=(s[i:i+3,j:j+3])
        print(n.sum())
        

45
45
45
45
45
45
45
45
45


#### general Questions ####

In [9]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])


#Get the shape of the matrix.

In [10]:
data.shape

(5, 3)

#Find the average age of students.

In [16]:
Age=data[:,0]
Age.mean()

np.float64(18.4)

#Extract Math marks of all students.

In [19]:
Maths=data[:,1]
Maths

array([85, 92, 76, 65, 90])

#Find the highest Science mark.

In [22]:
MaxSc=np.max(data[:,2])
MaxSc

np.int64(95)

#Get details of the student who scored more than 90 in Math.

In [23]:
Maths=data[:,1]
Maths

array([85, 92, 76, 65, 90])

In [28]:
for i in range (len(Maths)):
    if (Maths[i]>90):
        print(data[i])

[19 92 88]


#Increase Math marks of all students by 5.

In [29]:
Maths

array([85, 92, 76, 65, 90])

In [32]:
Inc=Maths+10
Inc

array([ 95, 102,  86,  75, 100])

#Find how many students are younger than 19.

In [33]:
Age=data[:,0]
Age


array([18, 19, 17, 18, 20])

In [37]:
count=0
for i in range (len(Age)):
    if (Age[i]<19):
        count+=1
print(count)

3


#Calculate the average marks in each subject (column-wise mean).

In [38]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [39]:
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

#Get data of students who scored at least 80 in both subjects.

In [40]:
data[(data[:,1]>=80)&(data[:,2]>=80)]

array([[19, 92, 88],
       [20, 90, 85]])

#Replace all Science marks < 75 with 0.

In [45]:
data[:,2][data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])